[project]
name = "day-005"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sunil Veeramachaneni", email = "sunil.veera@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "torch>=2.14.1",
    "transformers>=5.18.0",
]

[project.scripts]
day-005 = "day_005:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
