[project]
name = "day-003"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sunil Veeramachaneni", email = "sunil.veera@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
]

[project.scripts]
day-003 = "day_003:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
